version: 2

project_name: s3-sites

builds:
  - env:
      - CGO_ENABLED=0
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    flags: [-trimpath]
    ldflags: ["-s -w"]

archives:
  - formats: binary
    name_template: "{{ .Binary }}_{{ .Os }}-{{ .Arch }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

dockers_v2:
  - images:
      - "ghcr.io/reddec/s3-sites"
    platforms: [linux/amd64, linux/arm64]
    tags:
      - "{{ .Version }}"
      - "latest"
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
